spring:
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  profiles:
    active: dev2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/openexperiment?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    port: 6380
    host: localhost
    password: "123456"
mybatis:
  type-aliases-package: com.swpu.uchain.openexperiment.domain
  mapper-locations: classpath:mappers/*.xml
jwt:
  secret: swpu-uchain
  expiration: 43000
redis:
  host: localhost
  port: 6380
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
  password: "123456"
page:
  count:
    announcement: 10
    project: 5
    check-user: 10
    check-project: 7
    manage-user: 7
    manage-role: 7


